services:
  db-dev:
    image: mysql:8.3
    command: --sql_mode= --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ../../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: deepsound_db
    volumes:
      - deepsound-mysql-data-dev:/var/lib/mysql
    networks:
      - deepsound-net

networks:
  deepsound-net:

volumes:
  deepsound-mysql-data-dev:
    name: deepsound-mysql-data-dev