services:
  db:
    image: mysql:8.3
    command: --sql_mode= --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: passWord
      MYSQL_DATABASE: deepsound_db
    ports:
      - 3112:3112
    volumes:
      - deepsound-mysql-data:/var/lib/mysql
    networks:
      - deepsound-net

  deepsound:
    image: deepsound-php
    ports:
      - 3111:80
    volumes:
      - ./Script/:/var/www/html/
    depends_on:
      - db
    networks:
      - deepsound-net

  sendcoin:
    image: sendcoin-nodejs
    command: ['yarn', 'dev']
    ports:
      - 8888:8888
    volumes:
      - ./blockchainsendcoin:/app
    networks:
      - deepsound-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - deepsound-net

networks:
  deepsound-net:

volumes:
  deepsound-mysql-data:
    name: deepsound-mysql-data
