services:
  db:
    image: mysql:8.3
    command: --sql_mode= --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: deepsound_db
    volumes:
      - deepsound-mysql-data:/var/lib/mysql
    networks:
      - deepsound-net
  adminer:
    image: adminer
    restart: always
    ports:
      - 3113:8080
    networks:
      - deepsound-net

  deepsound:
    build: .
    ports:
      - 3111:80
    depends_on:
      - db
    networks:
      - deepsound-net
    volumes:
      - deepsound-data:/var/www/html/

networks:
  deepsound-net:

volumes:
  deepsound-mysql-data:
    name: deepsound-mysql-data
  deepsound-data:
    name: deepsound-data